# Generated by Django 4.1.7 on 2023-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
