# Generated by Django 4.1.7 on 2023-03-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_userprofile_resource_resource_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile'),
        ),
    ]
