# Generated by Django 4.1.7 on 2023-03-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_resource_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='resource',
        ),
    ]
