# Generated by Django 4.1.7 on 2023-04-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_userprofile_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('price_perKilo', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sender', models.CharField(max_length=200, null=True)),
                ('reciever', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
