# Generated by Django 4.1.7 on 2023-06-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='f',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
