# Generated by Django 4.1.7 on 2023-06-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_post_f'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='report_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='f',
        ),
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
